In [1]:
import numpy as np
from scipy.linalg import solve, det, inv

## Zadanie 4

In [54]:
A_4 = np.array([
    [0, 0, 2, 1, 2],
    [0, 1, 0, 2, -1],
    [1, 2, 0, -2, 0],
    [0, 0, 0, -1, 1],
    [0, 1, -1, 1, -1]
])

b_4 = np.array([1, 1, -4, -2, -1])

In [2]:
def gaussian_elimination(A, b):
    A_mod = A.copy()
    b_mod = b.copy()
    A_mod = A_mod.astype(float)
    b_mod = b_mod.astype(float)
    n = len(b)
    s = 0
    

    for i in range(n):
        max_row = np.argmax(np.abs(A_mod[i:, i])) + i
        if A_mod[max_row, i] == 0:
            raise ValueError("Macierz osobliwa — brak jednoznacznego rozwiązania.")
        
        if max_row != i:
            A_mod[[i, max_row]] = A_mod[[max_row, i]]
            b_mod[[i, max_row]] = b_mod[[max_row, i]]
            s += 1
        
        for j in range(i + 1, n):
            m = A_mod[j, i] / A_mod[i, i]
            A_mod[j, i:] -= m * A_mod[i, i:]
            b_mod[j] -= m * b_mod[i]
    
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        suma = np.dot(A_mod[i, i + 1:], x[i + 1:])
        x[i] = (b_mod[i] - suma) / A_mod[i, i]
    
    return x, A_mod, s

In [56]:
x_4, At_4, _ = gaussian_elimination(A_4, b_4)
print(x_4)

[ 2. -2.  1.  1. -1.]


In [57]:
x_4_scipy = solve(A_4, b_4)
print(x_4_scipy)

[ 2. -2.  1.  1. -1.]


## Zadanie 5

In [58]:
punkty = np.array([[0, -1], [1, 1], [3, 3], [5, 2], [6, -2]])
punkty = punkty.astype(float)
b_5 = punkty[:,1]

a_5 = punkty[:,0]

A_5 = np.zeros((5,5))
for i in range(len(a_5)):
    for j in range(len(a_5)):
        A_5[i, j] = a_5[i]**j

np.set_printoptions(suppress=True)
print(A_5)
print(b_5)

[[   1.    0.    0.    0.    0.]
 [   1.    1.    1.    1.    1.]
 [   1.    3.    9.   27.   81.]
 [   1.    5.   25.  125.  625.]
 [   1.    6.   36.  216. 1296.]]
[-1.  1.  3.  2. -2.]


In [59]:
x_5, At_5, _ = gaussian_elimination(A_5, b_5)
print(x_5)
print(At_5)

[-1.          2.68333333 -0.875       0.21666667 -0.025     ]
[[   1.    0.    0.    0.    0.]
 [   0.    6.   36.  216. 1296.]
 [   0.    0.   -9.  -81. -567.]
 [   0.    0.    0.  -10. -140.]
 [   0.    0.    0.    0.  -40.]]


In [60]:
x_5_scipy = solve(A_5, b_5)
print(x_5_scipy)

[-1.          2.68333333 -0.875       0.21666667 -0.025     ]


## Zadanie 6

In [61]:
A_6 = np.array([
    [3.5, 2.77, -0.76, 1.8],
    [-1.8, 2.68, 3.44, -0.09],
    [0.27, 5.07, 6.9, 1.61],
    [1.71, 5.45, 2.68, 1.71]
    ])

b_6 = np.array([7.31, 4.23, 13.85, 11.55])

In [63]:
x_6, At_6, s_6 = gaussian_elimination(A_6, b_6)
print(x_6)

[1. 1. 1. 1.]


In [64]:
x_6_scipy = solve(A_6, b_6)
print(x_6_scipy)

[1. 1. 1. 1.]


In [65]:
def det_triangular(A, s):
    d = (-1)**s
    for i in range(len(A)):
        d *= A[i, i]
    return d

In [66]:
detA_6 = det_triangular(At_6, s_6)
print(detA_6)

-0.22579734000000884


In [67]:
detA_6 = det(A_6)
print(detA_6)

-0.22579733999999502


In [94]:
print(A_6 @ x_6)

[ 7.31  4.23 13.85 11.55]


## Zadanie 7

In [68]:
A_7 = np.array([
    [10, -2, -1, 2, 3, 1, -4, 7],
    [5, 11, 3, 10, -3, 3, 3, -4],
    [7, 12, 1, 5, 3, -12, 2, 3],
    [8, 7, -2, 1, 3, 2, 2, 4],
    [2, -15, -1, 1, 4, -1, 8, 3],
    [4, 2, 9, 1, 12, -1, 4, 1],
    [-1, 4, -7, -1, 1, 1, -1, -3],
    [-1, 3, 4, 1, 3, -4, 7, 6]
])

b_7 = np.array([0, 12, -5, 3, -25, -26, 9, -7])

In [69]:
x_7, At_7, _ = gaussian_elimination(A_7, b_7)
print(x_7)

[-1.  1. -1.  1. -1.  1. -1.  1.]


In [70]:
x_7_scipy = solve(A_7, b_7)
print(x_7_scipy)

[-1.  1. -1.  1. -1.  1. -1.  1.]


## Zadanie 8

In [6]:
def norm1(A):
    return np.max(np.sum(abs(A), axis=0))

In [5]:
def find_inv_A(A):
    n = len(A)
    I = np.eye(n)
    inv_A = np.zeros((n, n))
    for i in range(len(I)):
        x, _, _ = gaussian_elimination(A, I[i])
        inv_A[:, i] = x
    return inv_A

In [72]:
A_8 = np.array([
    [2, -1, 0, 0, 0, 0],
    [-1, 2, -1, 0, 0, 0],
    [0, -1, 2, -1, 0, 0],
    [0, 0, -1, 2, -1, 0],
    [0, 0, 0, -1, 2, -1],
    [0, 0, 0, 0, -1, 5]
])

In [73]:
A_8_inv = find_inv_A(A_8)
print(A_8_inv)

[[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]


In [74]:
A_8_inv_scipy = inv(A_8)
print(A_8_inv_scipy)

[[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]


In [101]:
print(A_8 @ A_8_inv)
print(A_8 @ A_8_inv_scipy)

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [-0. -0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [-0. -0.  0.  0. -0.  1.]]
[[ 1.  0.  0.  0.  0.  0.]
 [-0.  1. -0. -0. -0. -0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [-0. -0. -0. -0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]


In [113]:
print(norm1(A_8))

6


## Zadanie 9

In [3]:
A_9 = np.array([
    [1, 3, -9, 6, 4],
    [2, -1, 6, 7, 1],
    [3, 2, -3, 15, 5],
    [8, -1, 1, 4, 2],
    [11, 1, -2, 18, 7]
])

In [11]:
A_9_inv = find_inv_A(A_9)
print(A_9_inv)

[[-7.42166231e+14 -7.42166231e+14 -7.42166231e+14 -1.48433246e+15
   1.48433246e+15]
 [-3.52528960e+15 -3.52528960e+15 -3.52528960e+15 -7.05057919e+15
   7.05057919e+15]
 [-5.90359502e+14 -5.90359502e+14 -5.90359502e+14 -1.18071900e+15
   1.18071900e+15]
 [-0.00000000e+00 -0.00000000e+00  1.00000000e+00  1.00000000e+00
  -1.00000000e+00]
 [ 1.50119988e+15  1.50119988e+15  1.50119988e+15  3.00239975e+15
  -3.00239975e+15]]


In [12]:
A_9_inv_scipy = inv(A_9)
print(A_9_inv_scipy)

[[-1.06340236e+15 -1.06340236e+15 -1.06340236e+15 -2.12680472e+15
   2.12680472e+15]
 [-5.05116121e+15 -5.05116121e+15 -5.05116121e+15 -1.01023224e+16
   1.01023224e+16]
 [-8.45888241e+14 -8.45888241e+14 -8.45888241e+14 -1.69177648e+15
   1.69177648e+15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  1.00000000e+00
  -1.00000000e+00]
 [ 2.15097296e+15  2.15097296e+15  2.15097296e+15  4.30194591e+15
  -4.30194591e+15]]


In [100]:
print(A_9 @ A_9_inv)
print(A_9 @ A_9_inv_scipy)

[[ 0.    1.    1.    0.    0.  ]
 [ 0.    0.25 -0.25  0.    0.  ]
 [-1.    0.25  2.25  0.    0.  ]
 [-1.   -0.5   0.    1.   -1.  ]
 [-1.    0.75  0.75  0.    0.  ]]
[[ 2.    0.   -1.    0.    0.  ]
 [ 0.    1.    0.25  1.    0.  ]
 [ 1.5   2.    2.5   2.   -2.  ]
 [ 0.    0.    1.    2.    0.  ]
 [ 2.5   2.    1.5   6.    2.  ]]


In [120]:
print(norm1(A_9))
print(np.linalg.cond(A_9))

50
2.2186476036279408e+17
